Add Who said it best
dwayne/builtwithelm pull request #26
Opened 2022-09-09 04:06 UTC by pangyuehung

2022-09-11 20:51 UTC, dwayne requested changes

2022-09-11 20:51 UTC, dwayne commented on README.md
> +`public/data/projects.json` and add a screenshot in `public/data/images`.
Thanks for noticing and fixing the incorrect directory references.

2022-09-11 20:51 UTC, dwayne commented on public/data/projects.json
> +    "description": "Who Said It Best? is a simple quiz game to differentiate between a contemporary billionaire from the greatest tyrant of the last century."
You're missing a comma at the end.

2022-09-11 20:51 UTC, dwayne commented on public/data/projects.json
> +    "primaryUrl": "https://muskorhitler.com"
Same.

2022-09-11 20:51 UTC, dwayne commented on public/data/projects.json
> +  }
Same.

2022-09-11 21:00 UTC, dwayne commented
@pangyuehung I reviewed your app and it looks like your [Learn more about actual socialism](https://muskorhitler.com/url) link doesn't work.

Thanks for your contribution. However, I don't think I will be including this app on the site. If you want to submit a separate PR for the README changes that will be fine.

2022-09-12 15:44 UTC, pangyuehung commented
> link doesn't work

Fixed. No problem, thanks for the consideration

2022-09-12 15:44 UTC, closed without merging